# src/main/resources/config.properties
baseUrl=https://qa-intelligence.cognni.ai/
msft_url=https://qa-intelligence.cognni.ai/login
msft_user=user@CognniAutomations.onmicrosoft.com
msft_pass=automateMIP1