name: Cognni Automation CI

on:
  push:
    branches: [ main, master ] # run when push code on main or master branch
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest # run on Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Maven
        run: mvn clean test # run testng tests
        continue-on-error: true # run next steps even test failed

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages # get old report from gh-pages branch
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20 # keep maximum 20 reports

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history # upload allure report to website